### ISSUE TITLE
Plant phenotyping example

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#15]
## Summary

These todos were collected while testing the notebooks on plant images.

## TODO

- [ ] Work with images stored in non-flat file directories  
    - [ ] e.g., we can create unique IDs from the path: `plantID_data_filename`
- [ ] In annotation, we assume that all parent images are stored in one directory. Can we make this a bit more flexible, e.g., "/path/to/\*/\*.png"?
- [ ] Count the number of pixels in parent images (x and y), add as metadata
- [ ] Add a warning/error when the number of pixels in x or y directions are different from what we expect.
- [ ] Colorbars, transparency for out of the range patches?
- [x] normalize_mean and normalize_std in 003_train_classifier need to be set based on the plant images.
    - [ ] Refer: https://github.com/Living-with-machines/MapReader/issues/31 
- [ ] Data augmentation and transformations for the plant images, e.g., the intensities or brightness, mimic the changes in light/brightness.
- [x] Multiple views, compare different side-views, they should be the same scale (for each side view), transfer learning
- [ ] Change over time, which features emerge first
- [x] Chain of classifiers? The first classifier would decide plant/no and then classify the flower/greenspace, then the shape of the features. Classify green features into different groups.
    - [ ] Refer: https://github.com/Living-with-machines/MapReader/issues/32 
- [ ] torchvision and MapReader installation issue

**Comment by kasra-hosseini** [comment]
>  Chain of classifiers? The first classifier would decide plant/no and then classify the flower/greenspace, then the shape of the features. Classify green features into different groups.

- The first classifier has three labels : None / Flower / Leaf. The second classifier will be designed later.

**Comment by kasra-hosseini** [comment]
> Multiple views, compare different side-views, they should be the same scale (for each side view), transfer learning

- WIP, we have two sets of labelled data. One for top view and the other for side views. Training has been done only on the top view.

**Comment by kasra-hosseini** [comment]
> normalize_mean and normalize_std in 003_train_classifier need to be set based on the plant images.

Refer to: https://github.com/Living-with-machines/MapReader/issues/31

**Comment by dcsw2** [comment]
Hi @evangeline-corcoran is this ticket live? We are just doing some spring-cleaning of this board and would like to close it if possible? Do you need the contents somewhere else? If so can you move it?

**Comment by evangeline-corcoran** [comment]
Hi @dcsw2 I've moved the relevant info elsewhere, so you can go ahead and close this.
